In [1]:
import pandas as pd

# 🟢 Simple Section (10 Questions)

*Focus: Basic data inspection, filtering, selection, and simple aggregations.*

## Q1: Load the Titanic CSV dataset into a DataFrame called df and display its first 5 rows.

In [15]:
df = pd.read_csv('../docs/pandas/titanic_train.csv')

# df[:5]
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Q2: Find the total number of rows and columns present in this dataset.

In [18]:
shape = df.shape

print(f"Total Rows:     {shape[0]}")
print(f"Total Columns:  {shape[1]}")

Total Rows:     891
Total Columns:  12

## Q3: Print the names of all the columns and their respective data types.

In [24]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

## Q4: Calculate the average (mean) `Fare` paid by all the passengers.

In [31]:
df["Fare"].mean()

np.float64(32.204207968574636)

## Q5: Find out how many unique values exist in the `Embarked` column.

In [30]:
df["Embarked"].nunique()

3

## Q6: Filter the DataFrame to show only rows where passengers survived (`Survived == 1`).

In [32]:
df[df["Survived"] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

## Q7: Select only the `Name` and `Age` columns for passengers who were in 1st class (`Pclass == 1`).

In [39]:
df[df["Pclass"] == 1][["Name", "Age"]]

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
6                              McCarthy, Mr. Timothy J  54.0
11                            Bonnell, Miss. Elizabeth  58.0
23                        Sloper, Mr. William Thompson  28.0
..                                                 ...   ...
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0
872                           Carlsson, Mr. Frans Olof  33.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
887                       Graham, Miss. Margaret Edith  19.0
889                              Behr, Mr. Karl Howell  26.0

[216 rows x 2 columns]

## Q8: Count the exact number of missing (`NaN`) values in the `Age` column.

In [50]:
print(df["Age"].isna().sum())

177

## Q9: Rename the column `Sex` to `Gender` and `Pclass` to `Passenger_Class` permanently.

In [52]:
df.rename(columns={
    "Sex": "Gender",
    "Pclass": "Passenger_Class"
}, inplace=True)
print(df.columns)

Index(['PassengerId', 'Survived', 'Passenger_Class', 'Name', 'Gender', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

## Sort the entire DataFrame by the Fare column in descending order.

In [55]:
df.sort_values(by="Fare", ascending=False)

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
...,...,...,...,...,...,...,...,...,...,...,...,...
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0000,B102,S
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0000,NaN,S
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0000,NaN,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0000,NaN,S

# 🟡 Intermediate Section (10 Questions)
*Focus: Grouping, basic data cleaning, multi-conditional filtering, and basic string operations.*

## Q11: Find the survival rate (average of `Survived`) grouped by `Gender` (formerly `Sex`).

In [56]:
df.groupby(by="Gender")["Survived"].mean()

Gender
female    0.742038
male      0.188908
Name: Survived, dtype: float64

## Q12: Fill all the missing (`NaN`) values in the `Age` column with the median age of the dataset.

In [ ]:
df["Age"].fillna(df["Age"].median())

np.float64(28.0)

## Q13: Filter the dataset to find all female passengers who were over the age of 30 using the `.query()` method.

In [66]:
df.query("Gender == 'female' & Age > 30")

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q

## Q14: Create a new column named `FamilySize` by adding `SibSp` (siblings/spouses) and `Parch` (parents/children) together.

In [68]:
df["FamilySize"] = df["SibSp"] + df["Parch"]
df

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

## Q15: Find out which `Embarked` port had the highest number of passengers boarding.

In [70]:
df["Embarked"].value_counts().idxmax()

'S'

## Q16: Filter the DataFrame for passengers whose `Fare` was between $50 and $100 (inclusive) using `between()`.

In [76]:
df[df["Fare"].between(50, 100)]

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,0
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C,1
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C,1
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S,0
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,2
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,1

## Q17: Drop the `Cabin` column entirely from the DataFrame since it has too many missing values.

In [78]:
df.drop(columns=["Cabin"], inplace=True, errors="ignore")

In [79]:
df

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0

## Q18: Group the dataset by both `Passenger_Class` and `Gender`, and calculate the median `Fare` for each subgroup.

In [82]:
df.groupby(by=["Passenger_Class", "Gender"])["Fare"].median()

Passenger_Class  Gender
1                female    82.66455
                 male      41.26250
2                female    22.00000
                 male      13.00000
3                female    12.47500
                 male       7.92500
Name: Fare, dtype: float64

## Q19: Find the records of passengers whose names contain the specific title `"Master."`

In [83]:
df[df["Name"].str.contains('Master\.', na=False)]

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
C:\Users\mdkha\AppData\Local\Temp\ipykernel_8968\4206669307.py:1: SyntaxWarning: invalid escape sequence '\.'
  df[df["Name"].str.contains('Master\.', na=False)]

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,S,4
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,Q,5
50,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,S,5
59,60,0,3,"Goodwin, Master. William Frederick",male,11.00,5,2,CA 2144,46.9000,S,7
63,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,S,5
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,C,2
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,S,2
125,126,1,3,"Nicola-Yarred, Master. Elias",male,12.00,1,0,2651,11.2417,C,1
159,160,0,3,"Sage, Master. Thomas Henry",male,NaN,8,2,CA. 2343,69.5500,S,10
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,S,5
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,S,2
171,172,0,3,"Rice, Master. Arthur",male,4.00,4,1,382652,29.1250,Q,5
176,177,0,3,"Lefebre, Master. Henry Forbes",male,NaN,3,1,4133,25.4667,S,4
182,183,0,3,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4,2,347077,31.3875,S,6
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,S,3
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,S,2
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,S,6
278,279,0,3,"Rice, Master. Eric",male,7.00,4,1,382652,29.1250,Q,5
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,S,3
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,S,2
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,S,2
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,S,7
407,408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,S,2
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,S,2
480,481,0,3,"Goodwin, Master. Harold Victor",male,9.00,5,2,CA 2144,46.9000,S,7
489,490,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,S,2
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,S,2
709,710,1,3,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1,1,2661,15.2458,C,2
751,752,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,S,1
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,S,2
787,788,0,3,"Rice, Master. George Hugh",male,8.00,4,1,382652,29.1250,Q,5
788,789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,S,3
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,S,3
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,C,1
819,820,0,3,"Skoog, Master. Karl Thorsten",male,10.00,3,2,347088,27.9000,S,5
824,825,0,3,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,39.6875,S,5
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,C,2
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,S,2
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,S,6
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,S,2

## Q20: Check for duplicate rows based on the `Ticket` column and count how many duplicate tickets exist.

In [88]:
df["Ticket"].duplicated().sum()

np.int64(210)

# 🔴 Advanced Section (10 Questions)
*Focus: Custom transformations, aggregation maps, index manipulations, and advanced string splitting.*

## Q21: Use `groupby()` and `.agg()` to find the minimum, maximum, and mean age, along with the total number of survivors, for each `Passenger_Class`.

In [90]:
df.groupby(by=["Passenger_Class"]).agg({
    "Age": ["min", "max", "mean"],
    "Survived": "sum"
})

                  Age                  Survived
                  min   max       mean      sum
Passenger_Class
1                0.92  80.0  38.233441      136
2                0.67  70.0  29.877630       87
3                0.42  74.0  25.140620      119

## Q22: Create a custom function that categorizes age into `"Child"` (under 18), `"Adult"` (18–60), and `"Senior"` (above 60). Apply this function to create a new column called `AgeGroup`.

In [94]:
def categorize_age(age):
    if age < 18: return "Child"
    elif  age <= 60: return "Adult"
    else: return "Senior"

df["AgeGroup"] = df["Age"].apply(categorize_age)
df

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,1,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,0,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S,3,Senior
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,0,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0,Adult

## Q23: Find the names of the top 3 passengers who paid the absolute highest fares in 3rd class (`Passenger_Class == 3`).

In [95]:
df[df["Passenger_Class"] == 3].nlargest(3, 'Fare')

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,AgeGroup
159,160,0,3,"Sage, Master. Thomas Henry",male,NaN,8,2,CA. 2343,69.55,S,10,Senior
180,181,0,3,"Sage, Miss. Constance Gladys",female,NaN,8,2,CA. 2343,69.55,S,10,Senior
201,202,0,3,"Sage, Mr. Frederick",male,NaN,8,2,CA. 2343,69.55,S,10,Senior

## Q24: Extract the Surname (the text before the comma) from the `Name` column and store it in a new column called `Surname`.

In [97]:
df["Surname"] = df["Name"].str.split(',').str[0]
df

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,AgeGroup,Surname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,1,Adult,Braund
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1,Adult,Cumings
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0,Adult,Heikkinen
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1,Adult,Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0,Adult,Allen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0,Adult,Montvila
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,0,Adult,Graham
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S,3,Senior,Johnston
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,0,Adult,Behr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0,Adult,Dooley

## Q25: Use `pivot_table` to calculate the total number of survivors (`sum`) and total counts (`count`) cross-tabulated by `Passenger_Class` (rows) and `Gender` (columns).

In [98]:
df.pivot_table(index='Passenger_Class', columns='Gender', values='Survived', aggfunc=['sum', 'count'])

                   sum       count
Gender          female male female male
Passenger_Class
1                   91   45     94  122
2                   70   17     76  108
3                   72   47    144  347

## Q26: Identify the rows where a passenger's age is an outlier, defined here as being greater than 3 standard deviations from the dataset's mean age.

In [99]:
mean_age = df["Age"].mean()
std_age = df["Age"].std()
outlier = df[df["Age"] > (mean_age + 3 * std_age)]
outlier

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,AgeGroup,Surname
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.000,S,0,Senior,Barkworth
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.775,S,0,Senior,Svensson

## Q27: Group the data by `Passenger_Class` and replace the missing `Age` values within each class using that specific class's mean age (using `.transform()`).

In [100]:
df["Age"] = df.groupby("Passenger_Class")["Age"].transform(lambda x: x.fillna(x.mean()))

## Q28: Filter the dataset to only include passengers who are travelling completely alone (meaning their `FamilySize` calculated in Q14 is 0).

In [101]:
df[df["FamilySize"] == 0]

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,AgeGroup,Surname
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00000,0,0,STON/O2. 3101282,7.9250,S,0,Adult,Heikkinen
4,5,0,3,"Allen, Mr. William Henry",male,35.00000,0,0,373450,8.0500,S,0,Adult,Allen
5,6,0,3,"Moran, Mr. James",male,25.14062,0,0,330877,8.4583,Q,0,Senior,Moran
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.00000,0,0,17463,51.8625,S,0,Adult,McCarthy
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.00000,0,0,113783,26.5500,S,0,Adult,Bonnell
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.00000,0,0,SOTON/OQ 392076,7.0500,S,0,Adult,Sutehall
886,887,0,2,"Montvila, Rev. Juozas",male,27.00000,0,0,211536,13.0000,S,0,Adult,Montvila
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.00000,0,0,112053,30.0000,S,0,Adult,Graham
889,890,1,1,"Behr, Mr. Karl Howell",male,26.00000,0,0,111369,30.0000,C,0,Adult,Behr
890,891,0,3,"Dooley, Mr. Patrick",male,32.00000,0,0,370376,7.7500,Q,0,Adult,Dooley

## Q29: Convert the categorical Gender column into numerical indicators using binary mapping (`'male': 0, 'female': 1`).

In [102]:
df["Gender_Numeric"] = df["Gender"].map({"male": 0, "female": 1})
df

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,AgeGroup,Surname,Gender_Numeric
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00000,1,0,A/5 21171,7.2500,S,1,Adult,Braund,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00000,1,0,PC 17599,71.2833,C,1,Adult,Cumings,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00000,0,0,STON/O2. 3101282,7.9250,S,0,Adult,Heikkinen,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00000,1,0,113803,53.1000,S,1,Adult,Futrelle,1
4,5,0,3,"Allen, Mr. William Henry",male,35.00000,0,0,373450,8.0500,S,0,Adult,Allen,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.00000,0,0,211536,13.0000,S,0,Adult,Montvila,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.00000,0,0,112053,30.0000,S,0,Adult,Graham,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,25.14062,1,2,W./C. 6607,23.4500,S,3,Senior,Johnston,1
889,890,1,1,"Behr, Mr. Karl Howell",male,26.00000,0,0,111369,30.0000,C,0,Adult,Behr,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.00000,0,0,370376,7.7500,Q,0,Adult,Dooley,0

## Q30: Set the `PassengerId` column as the DataFrame index, and then select the passenger data for indices 100 to 110 using `.loc`.

In [105]:
df_indexed = df.set_index("PassengerId")
df_indexed.iloc[100:110]

,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,AgeGroup,Surname,Gender_Numeric
PassengerId,,,,,,,,,,,,,,
101,0,3,"Petranec, Miss. Matilda",female,28.00000,0,0,349245,7.8958,S,0,Adult,Petranec,1
102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,25.14062,0,0,349215,7.8958,S,0,Senior,Petroff,0
103,0,1,"White, Mr. Richard Frasar",male,21.00000,0,1,35281,77.2875,S,1,Adult,White,0
104,0,3,"Johansson, Mr. Gustaf Joel",male,33.00000,0,0,7540,8.6542,S,0,Adult,Johansson,0
105,0,3,"Gustafsson, Mr. Anders Vilhelm",male,37.00000,2,0,3101276,7.9250,S,2,Adult,Gustafsson,0
106,0,3,"Mionoff, Mr. Stoytcho",male,28.00000,0,0,349207,7.8958,S,0,Adult,Mionoff,0
107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.00000,0,0,343120,7.6500,S,0,Adult,Salkjelsvik,1
108,1,3,"Moss, Mr. Albert Johan",male,25.14062,0,0,312991,7.7750,S,0,Senior,Moss,0
109,0,3,"Rekic, Mr. Tido",male,38.00000,0,0,349249,7.8958,S,0,Adult,Rekic,0
110,1,3,"Moran, Miss. Bertha",female,25.14062,1,0,371110,24.1500,Q,1,Senior,Moran,1