### Pandas

pandas builds directly on top of NumPy, adding explicit row indices, named columns, and flexible file I/O designed for tabular data.

**1. The Core Data Structures: Series vs. DataFrame**

Think of a Series as a single column with an index, and a DataFrame as an entire spreadsheet table composed of multiple Series sharing the same index.

In [9]:
import pandas as pd
import numpy as np

In [2]:
# Series: 1D labeled array
ages = pd.Series([25, 30, 35], index=["Alice", "Bob", "Charlie"], name="age")
print(ages)

Alice      25
Bob        30
Charlie    35
Name: age, dtype: int64

In [3]:
# Dataframe 2D Level Data structure (columns can have different types)
data = {
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Tokyo"]
}
df = pd.DataFrame(data, index=["Alice", "Bob", "Charlie"])
print(df)

         Age      City
Alice     25  New York
Bob       30    London
Charlie   35     Tokyo

In [5]:
# Extracting one column from a DataFrame returs a Series: df["Age"]
print(df["City"])

Alice      New York
Bob          London
Charlie       Tokyo
Name: City, dtype: str

**2. Common Ways to Create DataFrames**

**From a Dictionary of Lists (Most Common)**

Keys become column headers; list items become row values.

In [7]:
data = {
    "Name": ["Laptop", "Monitor", "Keyboard"],
    "Price": [1000, 25, 10],
    "In_Stock": [True, True, False]
}
df = pd.DataFrame(data)
print(df)

       Name  Price  In_Stock
0    Laptop   1000      True
1   Monitor     25      True
2  Keyboard     10     False

**From a List of Dictionaries (Row-Oriented)**

Useful when consuming API responses or JSON records where each item represents a row.

In [8]:
records = [
    { "Name": "Laptop", "Price": 1000 },
    { "Name": "Monitor", "Price": 25 },
    { "Name": "Keyboard", "Price": 10 },
]
df = pd.DataFrame(records)
print(df)

       Name  Price
0    Laptop   1000
1   Monitor     25
2  Keyboard     10

**From a 2D NumPy Array**

Manually pass `columns` and optional `index` labels.

In [12]:
arr = np.random.randint(10, 100, size=(3,2))
print("Array")
print(arr)

df = pd.DataFrame(arr, columns=["Score_A", "Score_B"])
print("\nPandas")
print(df)

Array
[[79 47]
 [92 16]
 [76 88]]

Pandas
   Score_A  Score_B
0       79       47
1       92       16
2       76       88

**3. Ingesting Data From Files and Databases**

Pandas includes built-in parsers starting with `pd.read_*` that handle types, missing values, and structure automatically.

**Reading CSV: `pd.read_csv()`**

The standard comma-delimited text format.

In [ ]:
# Basic read
df = pd.read_csv("../docs/pandas/tips.csv")

# Usefull Parameters
df = pd.read_csv(
    "../docs/pandas/tips.csv",
    sep=",",                            # Delimiter (e.g. '\t' for tap-separated)
    header=0,                           # Row number to use as a column name
    usecols=["total_bill", "tip"],      # Load onlt specific columns (save RAM)
    na_values=["?", "NA"]               # Treat custom symbols as NAN missing values
)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]
     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

**Reading Excel: `pd.read_excel()`**

Reads `.xlsx` or `.xls` workbooks. Requires the `openpyxl` library installed.

In [21]:
# Read the fist sheet by default
df = pd.read_excel('../docs/pandas/Sample-Sales-Data.xlsx')
print(df)

     Postcode  Sales_Rep_ID Sales_Rep_Name  Year         Value
0        2121           456           Jane  2011  84219.497311
1        2092           789         Ashish  2012  28322.192268
2        2128           456           Jane  2013  81878.997241
3        2073           123           John  2011  44491.142121
4        2134           789         Ashish  2012  71837.720959
..        ...           ...            ...   ...           ...
385      2164           123           John  2012  88884.535217
386      2193           456           Jane  2013  79440.290813
387      2031           123           John  2011  65643.689454
388      2130           456           Jane  2012  66247.874869
389      2116           456           Jane  2013   3195.699054

[390 rows x 5 columns]

In [23]:
# Specific a sheet name or index
df = pd.read_excel("../docs/pandas/Sample-Sales-Data.xlsx", sheet_name="Sheet1")
print(df)

     Postcode  Sales_Rep_ID Sales_Rep_Name  Year         Value
0        2121           456           Jane  2011  84219.497311
1        2092           789         Ashish  2012  28322.192268
2        2128           456           Jane  2013  81878.997241
3        2073           123           John  2011  44491.142121
4        2134           789         Ashish  2012  71837.720959
..        ...           ...            ...   ...           ...
385      2164           123           John  2012  88884.535217
386      2193           456           Jane  2013  79440.290813
387      2031           123           John  2011  65643.689454
388      2130           456           Jane  2012  66247.874869
389      2116           456           Jane  2013   3195.699054

[390 rows x 5 columns]

In [24]:
# Skip introductory title rows
df = pd.read_excel("../docs/pandas/Sample-Sales-Data.xlsx", skiprows=2)
print(df)

     2092  789  Ashish  2012  28322.192268
0    2128  456    Jane  2013  81878.997241
1    2073  123    John  2011  44491.142121
2    2134  789  Ashish  2012  71837.720959
3    2162  123    John  2013  64531.549254
4    2093  456    Jane  2011  58962.639832
..    ...  ...     ...   ...           ...
383  2164  123    John  2012  88884.535217
384  2193  456    Jane  2013  79440.290813
385  2031  123    John  2011  65643.689454
386  2130  456    Jane  2012  66247.874869
387  2116  456    Jane  2013   3195.699054

[388 rows x 5 columns]

**Reading JSON: `pd.read_json()`**

Parses JSON strings or files into tabular format.

In [ ]:
# Direct json file ingestion
df = pd.read_json("../docs/pandas/world-population-by-country-2020.json")
print(df)

# Note: For deeply nested JSON, use json_normalize instead:
# import json
# with open("nested.json") as f:
#     data = json.load(f)
# df = pd.json_normalize(data, record_path=["items"], meta=["id"])

     position           country     population yearly_change  net_change  \
0           1             China  1,439,323,776        0.39 %   5,540,090
1           2             India  1,380,004,385        0.99 %  13,586,631
2           3     United States    331,002,651        0.59 %   1,937,734
3           4         Indonesia    273,523,615        1.07 %   2,898,047
4           5          Pakistan    220,892,340        2.00 %   4,327,022
..        ...               ...            ...           ...         ...
230       231        Montserrat          4,992        0.06 %           3
231       232  Falkland Islands          3,480        3.05 %         103
232       233              Niue          1,626        0.68 %          11
233       234           Tokelau          1,357        1.27 %          17
234       235          Holy See            801        0.25 %           2

    density_per_square_km land_are_in_square_km migrants_net fertility_rate  \
0                     153             9,388,211     -348,399            1.7
1                     464             2,973,190     -532,687            2.2
2                      36             9,147,420      954,806            1.8
3                     151             1,811,570      -98,955            2.3
4                     287               770,880     -233,379            3.6
..                    ...                   ...          ...            ...
230                    50                   100                        N.A.
231                     0                12,170                        N.A.
232                     6                   260                        N.A.
233                   136                    10                        N.A.
234                 2,003                     0                        N.A.

    median_age urban_population world_share
0           38             61 %     18.47 %
1           28             35 %     17.70 %
2           38             83 %      4.25 %
3           30             56 %      3.51 %
4           23             35 %      2.83 %
..         ...              ...         ...
230       N.A.             10 %      0.00 %
231       N.A.             66 %      0.00 %
232       N.A.             46 %      0.00 %
233       N.A.              0 %      0.00 %
234       N.A.             N.A.      0.00 %

[235 rows x 12 columns]

**Reading SQL: `pd.read_sql()`**

Executes an SQL query or reads a table directly via a database connection (typically created with SQLAlchemy).

In [ ]:
from sqlalchemy import create_engine

# 1. Establish the connection engine
engine = create_engine("sqlite:///company.db")
# Or PostgreSQL/MySQL: "postgresql://user:password@localhost:5432/mydb"

# 2. Query directly into a DataFrame
query = "SELECT user_id, email, signup_date FROM users WHERE active = 1"
df = pd.read_sql(query, con=engine)

# Alternatively, read an entire table without writing SQL
df_table = pd.read_sql_table("users", con=engine)

In [28]:
world_population = pd.read_json("../docs/pandas/world-population-by-country-2020.json")

## Data inspection

**1.** `df.head(n=5)` **&** `df.tail(n=5)`

Quickly preview the edges of the dataset to verify that headers loaded properly and rows look sensible.

- `df.head(n)`: Displays the first n rows (defaults to 5).
- `df.tail(n)`: Displays the last n rows (defaults to 5).

In [29]:
world_population.head(2)

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
0,1,China,"1,439,323,776",0.39 %,"5,540,090",153,"9,388,211","-348,399",1.7,38,61 %,18.47 %
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %

In [30]:
world_population.tail(2)

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
233,234,Tokelau,"1,357",1.27 %,17,136,10,,N.A.,N.A.,0 %,0.00 %
234,235,Holy See,801,0.25 %,2,"2,003",0,,N.A.,N.A.,N.A.,0.00 %

**2.** `df.shape`

Returns a tuple representing the matrix dimensions as 
`(number_of_rows, number_of_columns)`.

*Note: It is an **attribute**, so do not use parentheses ().*

In [31]:
world_population.shape

(235, 12)

**3.** `df.columns`

Returns an `Index` object containing all column header names. Useful for checking spelling, whitespace issues, or iterating over features.

*Note: It is an **attribute**, no parentheses.*

In [ ]:
print(world_population.columns)

# Common trick: convert to a plain text
print("-"*50)
world_population.columns.tolist()

Index(['position', 'country', 'population', 'yearly_change', 'net_change',
       'density_per_square_km', 'land_are_in_square_km', 'migrants_net',
       'fertility_rate', 'median_age', 'urban_population', 'world_share'],
      dtype='str')
--------------------------------------------------

['position',
 'country',
 'population',
 'yearly_change',
 'net_change',
 'density_per_square_km',
 'land_are_in_square_km',
 'migrants_net',
 'fertility_rate',
 'median_age',
 'urban_population',
 'world_share']

**4.** `df.dtypes`

Lists the inferred data type for each column (e.g., `int64`, `float64`, `object` for strings, `bool`, `datetime64`).

*Note: It is an ***attribute***, no parentheses.*

In [36]:
world_population.dtypes

position                 int64
country                    str
population                 str
yearly_change              str
net_change                 str
density_per_square_km      str
land_are_in_square_km      str
migrants_net               str
fertility_rate             str
median_age                 str
urban_population           str
world_share                str
dtype: object

**5.** `df.info()`

Provides a technical summary: total row count, column names, memory footprint, and **non-null counts** (essential for spotting missing values).

In [37]:
world_population.info()

<class 'pandas.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   position               235 non-null    int64
 1   country                235 non-null    str
 2   population             235 non-null    str
 3   yearly_change          235 non-null    str
 4   net_change             235 non-null    str
 5   density_per_square_km  235 non-null    str
 6   land_are_in_square_km  235 non-null    str
 7   migrants_net           235 non-null    str
 8   fertility_rate         235 non-null    str
 9   median_age             235 non-null    str
 10  urban_population       235 non-null    str
 11  world_share            235 non-null    str
dtypes: int64(1), str(11)
memory usage: 22.2 KB

**6.** `df.describe()`

Generates rapid 5-number summary statistics for numeric columns: count, mean, standard deviation, min, 25%, 50% (median), 75%, and max.

In [40]:
world_population.describe()

# Tip: Pass include='all' to get top frequency info for strings too:
# df.describe(include='all')

         position
count  235.000000
mean   118.000000
std     67.982841
min      1.000000
25%     59.500000
50%    118.000000
75%    176.500000
max    235.000000

**7.** `df.nunique()`

Counts the number of **unique values** across each column. Excellent for identifying categorical features versus identifiers/keys

In [41]:
world_population.nunique()

position                 235
country                  235
population               235
yearly_change            174
net_change               234
density_per_square_km    164
land_are_in_square_km    226
migrants_net             159
fertility_rate            51
median_age                35
urban_population          81
world_share               74
dtype: int64

**8.** `df.value_counts()`

Calculates the frequency distribution of distinct values. While it can run on an entire DataFrame to find duplicate rows, it is most commonly applied to a **single column (Series)** to see category counts.

In [ ]:
# Check frequency of values in a specific categorical column
world_population["median_age"].value_counts()

median_age
N.A.    34
19      14
28      12
32      11
43      11
18      10
42      10
20       9
30       8
38       7
40       7
26       7
22       7
24       7
17       6
31       6
34       6
33       5
29       5
44       5
45       5
41       5
21       5
23       4
25       4
37       4
36       4
46       3
35       3
27       3
39       3
47       2
48       1
15       1
16       1
Name: count, dtype: int64

In [43]:
# Tip: Get percentages instead of raw counts with normalize=
world_population["median_age"].value_counts(normalize=True)

median_age
N.A.    0.144681
19      0.059574
28      0.051064
32      0.046809
43      0.046809
18      0.042553
42      0.042553
20      0.038298
30      0.034043
38      0.029787
40      0.029787
26      0.029787
22      0.029787
24      0.029787
17      0.025532
31      0.025532
34      0.025532
33      0.021277
29      0.021277
44      0.021277
45      0.021277
41      0.021277
21      0.021277
23      0.017021
25      0.017021
37      0.017021
36      0.017021
46      0.012766
35      0.012766
27      0.012766
39      0.012766
47      0.008511
48      0.004255
15      0.004255
16      0.004255
Name: proportion, dtype: float64

**9.** `df["column"]` — **Single Column as a Series**

Passing a **single string** extracts just that column as a 1D Pandas `Series`.

In [51]:
countries = world_population["country"]

print("Data Type")
print(type(countries))

print("\ncountries")
print(world_population["country"])

Data Type
<class 'pandas.Series'>

countries
0                 China
1                 India
2         United States
3             Indonesia
4              Pakistan
             ...
230          Montserrat
231    Falkland Islands
232                Niue
233             Tokelau
234            Holy See
Name: country, Length: 235, dtype: str

**10.** `df[["col1", "col2"]]` — **Multiple Columns as a DataFrame**

Passing a list of column names (note the double brackets `[[...]]`) returns a new 2D `DataFrame`, preserving tabular structure.

*Tip: Even for a single column, `df[["City"]]` forces the output to remain a DataFrame rather than decaying into a Series.*

In [46]:
subset = world_population[["country", "world_share"]]

print("Datatype")
print(type(subset))

print("\nSubset")
print(subset)

Datatype
<class 'pandas.DataFrame'>

Subset
              country world_share
0               China     18.47 %
1               India     17.70 %
2       United States      4.25 %
3           Indonesia      3.51 %
4            Pakistan      2.83 %
..                ...         ...
230        Montserrat      0.00 %
231  Falkland Islands      0.00 %
232              Niue      0.00 %
233           Tokelau      0.00 %
234          Holy See      0.00 %

[235 rows x 2 columns]

**11.** `df.loc[]` — **Label-Based Selection:** `[row_label, col_label]`

`loc` works exclusively with **explicit index and column names.**

- **Rule**: When slicing with `loc` (`"r1":"r3"`), the endpoint is inclusive.

In [68]:
# Select a single cell:
world_population.loc[0, "country"]

'China'

In [67]:
# Select rows by label:
world_population.loc[0]

position                             1
country                          China
population               1,439,323,776
yearly_change                   0.39 %
net_change                   5,540,090
density_per_square_km              153
land_are_in_square_km        9,388,211
migrants_net                  -348,399
fertility_rate                     1.7
median_age                          38
urban_population                  61 %
world_share                    18.47 %
Name: 0, dtype: object

In [70]:
# Row slice: both 'r0' and 'r2' are INCLUDED
world_population.loc[0 : 5]

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
0,1,China,"1,439,323,776",0.39 %,"5,540,090",153,"9,388,211","-348,399",1.7,38,61 %,18.47 %
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %
2,3,United States,"331,002,651",0.59 %,"1,937,734",36,"9,147,420","954,806",1.8,38,83 %,4.25 %
3,4,Indonesia,"273,523,615",1.07 %,"2,898,047",151,"1,811,570","-98,955",2.3,30,56 %,3.51 %
4,5,Pakistan,"220,892,340",2.00 %,"4,327,022",287,"770,880","-233,379",3.6,23,35 %,2.83 %
5,6,Brazil,"212,559,417",0.72 %,"1,509,890",25,"8,358,140","21,200",1.7,33,88 %,2.73 %

In [72]:
# Select specific rows AND columns:
world_population.loc[0: 10, ["country", "world_share"]]

          country world_share
0           China     18.47 %
1           India     17.70 %
2   United States      4.25 %
3       Indonesia      3.51 %
4        Pakistan      2.83 %
5          Brazil      2.73 %
6         Nigeria      2.64 %
7      Bangladesh      2.11 %
8          Russia      1.87 %
9          Mexico      1.65 %
10          Japan      1.62 %

In [77]:
# Conditional row filtering with loc:
world_population.loc[world_population["position"] > 10, ["country", "world_share"]]

              country world_share
10              Japan      1.62 %
11           Ethiopia      1.47 %
12        Philippines      1.41 %
13              Egypt      1.31 %
14            Vietnam      1.25 %
..                ...         ...
230        Montserrat      0.00 %
231  Falkland Islands      0.00 %
232              Niue      0.00 %
233           Tokelau      0.00 %
234          Holy See      0.00 %

[225 rows x 2 columns]

In [79]:
world_population.loc[(world_population["position"] > 10) & (world_population["position"] < 20), ["country", "world_share"]]

        country world_share
10        Japan      1.62 %
11     Ethiopia      1.47 %
12  Philippines      1.41 %
13        Egypt      1.31 %
14      Vietnam      1.25 %
15     DR Congo      1.15 %
16       Turkey      1.08 %
17         Iran      1.08 %
18      Germany      1.07 %

**12.** `df.iloc[]` — **Integer Position-Based Selection:** `[row_idx, col_idx]`

`iloc` (integer location) completely ignores index labels and column names, relying strictly on **zero-based numeric coordinates ($0, 1, 2, \dots$)**, identical to NumPy.

- **Rule**: Slicing with `iloc` follows standard Python rules: the end index is **exclusive**.

In [78]:
print(world_population.iloc[0:2, 0:2])

   position country
0         1   China
1         2   India

**13.** `isin()` — **Multiple OR Conditions for Values**

Instead of writing 

`(df["City"] == "Paris") | (df["City"] == "Rome") | (df["City"] == "Berlin")`, 

pass an iterable (list, set, tuple) to `isin()`.

- It generates a **boolean mask** (`True` if the element matches anything in the list).

In [80]:
# Select rows where city is either India, China and Indonesia
cities = ["India", "China", "Indonesia"]
world_population[world_population["country"].isin(cities)]

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
0,1,China,"1,439,323,776",0.39 %,"5,540,090",153,"9,388,211","-348,399",1.7,38,61 %,18.47 %
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %
3,4,Indonesia,"273,523,615",1.07 %,"2,898,047",151,"1,811,570","-98,955",2.3,30,56 %,3.51 %

**14.** Negation (NOT IN)

Prefix the condition with `~` to exclude items:

In [82]:
# Select rows where city is NOT in India, China and Indonesia
cities = ["India", "China", "Indonesia"]
world_population[~world_population["country"].isin(cities)]

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
2,3,United States,"331,002,651",0.59 %,"1,937,734",36,"9,147,420","954,806",1.8,38,83 %,4.25 %
4,5,Pakistan,"220,892,340",2.00 %,"4,327,022",287,"770,880","-233,379",3.6,23,35 %,2.83 %
5,6,Brazil,"212,559,417",0.72 %,"1,509,890",25,"8,358,140","21,200",1.7,33,88 %,2.73 %
6,7,Nigeria,"206,139,589",2.58 %,"5,175,990",226,"910,770","-60,000",5.4,18,52 %,2.64 %
7,8,Bangladesh,"164,689,383",1.01 %,"1,643,222","1,265","130,170","-369,501",2.1,28,39 %,2.11 %
...,...,...,...,...,...,...,...,...,...,...,...,...
230,231,Montserrat,"4,992",0.06 %,3,50,100,,N.A.,N.A.,10 %,0.00 %
231,232,Falkland Islands,"3,480",3.05 %,103,0,"12,170",,N.A.,N.A.,66 %,0.00 %
232,233,Niue,"1,626",0.68 %,11,6,260,,N.A.,N.A.,46 %,0.00 %
233,234,Tokelau,"1,357",1.27 %,17,136,10,,N.A.,N.A.,0 %,0.00 %
234,235,Holy See,801,0.25 %,2,"2,003",0,,N.A.,N.A.,N.A.,0.00 %

**15.** `between()` — **Range Filtering (Lower & Upper Bound)**

Instead of writing `(df["Age"] >= 25) & (df["Age"] <= 35)`, `between()` checks whether numeric or datetime values fall inside a range.

- **Syntax**: `df["col"].between(left, right, inclusive="both")`
- `inclusive` options: `"both"` (default), `"neither"`, `"left"`, or `"right"`.

In [ ]:
# Filter position between 50 and 60 (inclusive)
world_population[world_population["position"].between(50, 60)]

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
49,50,Venezuela,"28,435,940",-0.28 %,"-79,889",32,"882,050","-653,249",2.3,30,N.A.,0.36 %
50,51,Madagascar,"27,691,018",2.68 %,"721,711",48,"581,795","-1,500",4.1,20,39 %,0.36 %
51,52,Cameroon,"26,545,863",2.59 %,"669,483",56,"472,710","-4,800",4.6,19,56 %,0.34 %
52,53,Côte d'Ivoire,"26,378,274",2.57 %,"661,730",83,"318,000","-8,000",4.7,19,51 %,0.34 %
53,54,North Korea,"25,778,816",0.44 %,"112,655",214,"120,410","-5,403",1.9,35,63 %,0.33 %
54,55,Australia,"25,499,884",1.18 %,"296,686",3,"7,682,300","158,246",1.8,38,86 %,0.33 %
55,56,Niger,"24,206,644",3.84 %,"895,929",19,"1,266,700","4,000",7.0,15,17 %,0.31 %
56,57,Taiwan,"23,816,775",0.18 %,"42,899",673,"35,410","30,001",1.2,42,79 %,0.31 %
57,58,Sri Lanka,"21,413,249",0.42 %,"89,516",341,"62,710","-97,986",2.2,34,18 %,0.27 %
58,59,Burkina Faso,"20,903,273",2.86 %,"581,895",76,"273,600","-25,000",5.2,18,31 %,0.27 %
59,60,Mali,"20,250,833",3.02 %,"592,802",17,"1,220,190","-40,000",5.9,16,44 %,0.26 %

In [ ]:
# Exclusive Range Check
# Position > 4 AND Position < 8
world_population[world_population["position"].between(4,8, inclusive="neither")]

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
4,5,Pakistan,"220,892,340",2.00 %,"4,327,022",287,"770,880","-233,379",3.6,23,35 %,2.83 %
5,6,Brazil,"212,559,417",0.72 %,"1,509,890",25,"8,358,140","21,200",1.7,33,88 %,2.73 %
6,7,Nigeria,"206,139,589",2.58 %,"5,175,990",226,"910,770","-60,000",5.4,18,52 %,2.64 %

**16.** `query()` — **SQL-Style String Expressions**

`df.query()` evaluates an expression string. It eliminates repetitive references like `df[...]` and handles complex logical expressions cleanly.

**Basic Comparisons and Multiple Conditions**

Inside the query string, use standard words like `and`, `or`, `in`, and `not`.

In [86]:
world_population.query("country == 'India'")

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %

In [89]:
world_population.query("country in ['India', 'China']")

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
0,1,China,"1,439,323,776",0.39 %,"5,540,090",153,"9,388,211","-348,399",1.7,38,61 %,18.47 %
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %

In [91]:
country = "India"
world_population.query("country == @country")

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %