### Pandas

pandas builds directly on top of NumPy, adding explicit row indices, named columns, and flexible file I/O designed for tabular data.

**1. The Core Data Structures: Series vs. DataFrame**

Think of a Series as a single column with an index, and a DataFrame as an entire spreadsheet table composed of multiple Series sharing the same index.

In [2]:
import pandas as pd
import numpy as np

In [2]:
# Series: 1D labeled array
ages = pd.Series([25, 30, 35], index=["Alice", "Bob", "Charlie"], name="age")
print(ages)

Alice      25
Bob        30
Charlie    35
Name: age, dtype: int64

In [3]:
# Dataframe 2D Level Data structure (columns can have different types)
data = {
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Tokyo"]
}
df = pd.DataFrame(data, index=["Alice", "Bob", "Charlie"])
print(df)

         Age      City
Alice     25  New York
Bob       30    London
Charlie   35     Tokyo

In [5]:
# Extracting one column from a DataFrame returs a Series: df["Age"]
print(df["City"])

Alice      New York
Bob          London
Charlie       Tokyo
Name: City, dtype: str

**2. Common Ways to Create DataFrames**

**From a Dictionary of Lists (Most Common)**

Keys become column headers; list items become row values.

In [7]:
data = {
    "Name": ["Laptop", "Monitor", "Keyboard"],
    "Price": [1000, 25, 10],
    "In_Stock": [True, True, False]
}
df = pd.DataFrame(data)
print(df)

       Name  Price  In_Stock
0    Laptop   1000      True
1   Monitor     25      True
2  Keyboard     10     False

**From a List of Dictionaries (Row-Oriented)**

Useful when consuming API responses or JSON records where each item represents a row.

In [8]:
records = [
    { "Name": "Laptop", "Price": 1000 },
    { "Name": "Monitor", "Price": 25 },
    { "Name": "Keyboard", "Price": 10 },
]
df = pd.DataFrame(records)
print(df)

       Name  Price
0    Laptop   1000
1   Monitor     25
2  Keyboard     10

**From a 2D NumPy Array**

Manually pass `columns` and optional `index` labels.

In [12]:
arr = np.random.randint(10, 100, size=(3,2))
print("Array")
print(arr)

df = pd.DataFrame(arr, columns=["Score_A", "Score_B"])
print("\nPandas")
print(df)

Array
[[79 47]
 [92 16]
 [76 88]]

Pandas
   Score_A  Score_B
0       79       47
1       92       16
2       76       88

**3. Ingesting Data From Files and Databases**

Pandas includes built-in parsers starting with `pd.read_*` that handle types, missing values, and structure automatically.

**Reading CSV: `pd.read_csv()`**

The standard comma-delimited text format.

In [ ]:
# Basic read
df = pd.read_csv("../docs/pandas/tips.csv")

# Usefull Parameters
df = pd.read_csv(
    "../docs/pandas/tips.csv",
    sep=",",                            # Delimiter (e.g. '\t' for tap-separated)
    header=0,                           # Row number to use as a column name
    usecols=["total_bill", "tip"],      # Load onlt specific columns (save RAM)
    na_values=["?", "NA"]               # Treat custom symbols as NAN missing values
)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]
     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

**Reading Excel: `pd.read_excel()`**

Reads `.xlsx` or `.xls` workbooks. Requires the `openpyxl` library installed.

In [21]:
# Read the fist sheet by default
df = pd.read_excel('../docs/pandas/Sample-Sales-Data.xlsx')
print(df)

     Postcode  Sales_Rep_ID Sales_Rep_Name  Year         Value
0        2121           456           Jane  2011  84219.497311
1        2092           789         Ashish  2012  28322.192268
2        2128           456           Jane  2013  81878.997241
3        2073           123           John  2011  44491.142121
4        2134           789         Ashish  2012  71837.720959
..        ...           ...            ...   ...           ...
385      2164           123           John  2012  88884.535217
386      2193           456           Jane  2013  79440.290813
387      2031           123           John  2011  65643.689454
388      2130           456           Jane  2012  66247.874869
389      2116           456           Jane  2013   3195.699054

[390 rows x 5 columns]

In [23]:
# Specific a sheet name or index
df = pd.read_excel("../docs/pandas/Sample-Sales-Data.xlsx", sheet_name="Sheet1")
print(df)

     Postcode  Sales_Rep_ID Sales_Rep_Name  Year         Value
0        2121           456           Jane  2011  84219.497311
1        2092           789         Ashish  2012  28322.192268
2        2128           456           Jane  2013  81878.997241
3        2073           123           John  2011  44491.142121
4        2134           789         Ashish  2012  71837.720959
..        ...           ...            ...   ...           ...
385      2164           123           John  2012  88884.535217
386      2193           456           Jane  2013  79440.290813
387      2031           123           John  2011  65643.689454
388      2130           456           Jane  2012  66247.874869
389      2116           456           Jane  2013   3195.699054

[390 rows x 5 columns]

In [24]:
# Skip introductory title rows
df = pd.read_excel("../docs/pandas/Sample-Sales-Data.xlsx", skiprows=2)
print(df)

     2092  789  Ashish  2012  28322.192268
0    2128  456    Jane  2013  81878.997241
1    2073  123    John  2011  44491.142121
2    2134  789  Ashish  2012  71837.720959
3    2162  123    John  2013  64531.549254
4    2093  456    Jane  2011  58962.639832
..    ...  ...     ...   ...           ...
383  2164  123    John  2012  88884.535217
384  2193  456    Jane  2013  79440.290813
385  2031  123    John  2011  65643.689454
386  2130  456    Jane  2012  66247.874869
387  2116  456    Jane  2013   3195.699054

[388 rows x 5 columns]

**Reading JSON: `pd.read_json()`**

Parses JSON strings or files into tabular format.

In [ ]:
# Direct json file ingestion
df = pd.read_json("../docs/pandas/world-population-by-country-2020.json")
print(df)

# Note: For deeply nested JSON, use json_normalize instead:
# import json
# with open("nested.json") as f:
#     data = json.load(f)
# df = pd.json_normalize(data, record_path=["items"], meta=["id"])

     position           country     population yearly_change  net_change  \
0           1             China  1,439,323,776        0.39 %   5,540,090
1           2             India  1,380,004,385        0.99 %  13,586,631
2           3     United States    331,002,651        0.59 %   1,937,734
3           4         Indonesia    273,523,615        1.07 %   2,898,047
4           5          Pakistan    220,892,340        2.00 %   4,327,022
..        ...               ...            ...           ...         ...
230       231        Montserrat          4,992        0.06 %           3
231       232  Falkland Islands          3,480        3.05 %         103
232       233              Niue          1,626        0.68 %          11
233       234           Tokelau          1,357        1.27 %          17
234       235          Holy See            801        0.25 %           2

    density_per_square_km land_are_in_square_km migrants_net fertility_rate  \
0                     153             9,388,211     -348,399            1.7
1                     464             2,973,190     -532,687            2.2
2                      36             9,147,420      954,806            1.8
3                     151             1,811,570      -98,955            2.3
4                     287               770,880     -233,379            3.6
..                    ...                   ...          ...            ...
230                    50                   100                        N.A.
231                     0                12,170                        N.A.
232                     6                   260                        N.A.
233                   136                    10                        N.A.
234                 2,003                     0                        N.A.

    median_age urban_population world_share
0           38             61 %     18.47 %
1           28             35 %     17.70 %
2           38             83 %      4.25 %
3           30             56 %      3.51 %
4           23             35 %      2.83 %
..         ...              ...         ...
230       N.A.             10 %      0.00 %
231       N.A.             66 %      0.00 %
232       N.A.             46 %      0.00 %
233       N.A.              0 %      0.00 %
234       N.A.             N.A.      0.00 %

[235 rows x 12 columns]

**Reading SQL: `pd.read_sql()`**

Executes an SQL query or reads a table directly via a database connection (typically created with SQLAlchemy).

In [ ]:
from sqlalchemy import create_engine

# 1. Establish the connection engine
engine = create_engine("sqlite:///company.db")
# Or PostgreSQL/MySQL: "postgresql://user:password@localhost:5432/mydb"

# 2. Query directly into a DataFrame
query = "SELECT user_id, email, signup_date FROM users WHERE active = 1"
df = pd.read_sql(query, con=engine)

# Alternatively, read an entire table without writing SQL
df_table = pd.read_sql_table("users", con=engine)

In [28]:
world_population = pd.read_json("../docs/pandas/world-population-by-country-2020.json")

## Data inspection

**1.** `df.head(n=5)` **&** `df.tail(n=5)`

Quickly preview the edges of the dataset to verify that headers loaded properly and rows look sensible.

- `df.head(n)`: Displays the first n rows (defaults to 5).
- `df.tail(n)`: Displays the last n rows (defaults to 5).

In [29]:
world_population.head(2)

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
0,1,China,"1,439,323,776",0.39 %,"5,540,090",153,"9,388,211","-348,399",1.7,38,61 %,18.47 %
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %

In [30]:
world_population.tail(2)

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
233,234,Tokelau,"1,357",1.27 %,17,136,10,,N.A.,N.A.,0 %,0.00 %
234,235,Holy See,801,0.25 %,2,"2,003",0,,N.A.,N.A.,N.A.,0.00 %

**2.** `df.shape`

Returns a tuple representing the matrix dimensions as 
`(number_of_rows, number_of_columns)`.

*Note: It is an **attribute**, so do not use parentheses ().*

In [31]:
world_population.shape

(235, 12)

**3.** `df.columns`

Returns an `Index` object containing all column header names. Useful for checking spelling, whitespace issues, or iterating over features.

*Note: It is an **attribute**, no parentheses.*

In [ ]:
print(world_population.columns)

# Common trick: convert to a plain text
print("-"*50)
world_population.columns.tolist()

Index(['position', 'country', 'population', 'yearly_change', 'net_change',
       'density_per_square_km', 'land_are_in_square_km', 'migrants_net',
       'fertility_rate', 'median_age', 'urban_population', 'world_share'],
      dtype='str')
--------------------------------------------------

['position',
 'country',
 'population',
 'yearly_change',
 'net_change',
 'density_per_square_km',
 'land_are_in_square_km',
 'migrants_net',
 'fertility_rate',
 'median_age',
 'urban_population',
 'world_share']

**4.** `df.dtypes`

Lists the inferred data type for each column (e.g., `int64`, `float64`, `object` for strings, `bool`, `datetime64`).

*Note: It is an ***attribute***, no parentheses.*

In [36]:
world_population.dtypes

position                 int64
country                    str
population                 str
yearly_change              str
net_change                 str
density_per_square_km      str
land_are_in_square_km      str
migrants_net               str
fertility_rate             str
median_age                 str
urban_population           str
world_share                str
dtype: object

**5.** `df.info()`

Provides a technical summary: total row count, column names, memory footprint, and **non-null counts** (essential for spotting missing values).

In [37]:
world_population.info()

<class 'pandas.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   position               235 non-null    int64
 1   country                235 non-null    str
 2   population             235 non-null    str
 3   yearly_change          235 non-null    str
 4   net_change             235 non-null    str
 5   density_per_square_km  235 non-null    str
 6   land_are_in_square_km  235 non-null    str
 7   migrants_net           235 non-null    str
 8   fertility_rate         235 non-null    str
 9   median_age             235 non-null    str
 10  urban_population       235 non-null    str
 11  world_share            235 non-null    str
dtypes: int64(1), str(11)
memory usage: 22.2 KB

**6.** `df.describe()`

Generates rapid 5-number summary statistics for numeric columns: count, mean, standard deviation, min, 25%, 50% (median), 75%, and max.

In [40]:
world_population.describe()

# Tip: Pass include='all' to get top frequency info for strings too:
# df.describe(include='all')

         position
count  235.000000
mean   118.000000
std     67.982841
min      1.000000
25%     59.500000
50%    118.000000
75%    176.500000
max    235.000000

**7.** `df.nunique()`

Counts the number of **unique values** across each column. Excellent for identifying categorical features versus identifiers/keys

In [41]:
world_population.nunique()

position                 235
country                  235
population               235
yearly_change            174
net_change               234
density_per_square_km    164
land_are_in_square_km    226
migrants_net             159
fertility_rate            51
median_age                35
urban_population          81
world_share               74
dtype: int64

**8.** `df.value_counts()`

Calculates the frequency distribution of distinct values. While it can run on an entire DataFrame to find duplicate rows, it is most commonly applied to a **single column (Series)** to see category counts.

In [ ]:
# Check frequency of values in a specific categorical column
world_population["median_age"].value_counts()

median_age
N.A.    34
19      14
28      12
32      11
43      11
18      10
42      10
20       9
30       8
38       7
40       7
26       7
22       7
24       7
17       6
31       6
34       6
33       5
29       5
44       5
45       5
41       5
21       5
23       4
25       4
37       4
36       4
46       3
35       3
27       3
39       3
47       2
48       1
15       1
16       1
Name: count, dtype: int64

In [43]:
# Tip: Get percentages instead of raw counts with normalize=
world_population["median_age"].value_counts(normalize=True)

median_age
N.A.    0.144681
19      0.059574
28      0.051064
32      0.046809
43      0.046809
18      0.042553
42      0.042553
20      0.038298
30      0.034043
38      0.029787
40      0.029787
26      0.029787
22      0.029787
24      0.029787
17      0.025532
31      0.025532
34      0.025532
33      0.021277
29      0.021277
44      0.021277
45      0.021277
41      0.021277
21      0.021277
23      0.017021
25      0.017021
37      0.017021
36      0.017021
46      0.012766
35      0.012766
27      0.012766
39      0.012766
47      0.008511
48      0.004255
15      0.004255
16      0.004255
Name: proportion, dtype: float64

**9.** `df["column"]` — **Single Column as a Series**

Passing a **single string** extracts just that column as a 1D Pandas `Series`.

In [51]:
countries = world_population["country"]

print("Data Type")
print(type(countries))

print("\ncountries")
print(world_population["country"])

Data Type
<class 'pandas.Series'>

countries
0                 China
1                 India
2         United States
3             Indonesia
4              Pakistan
             ...
230          Montserrat
231    Falkland Islands
232                Niue
233             Tokelau
234            Holy See
Name: country, Length: 235, dtype: str

**10.** `df[["col1", "col2"]]` — **Multiple Columns as a DataFrame**

Passing a list of column names (note the double brackets `[[...]]`) returns a new 2D `DataFrame`, preserving tabular structure.

*Tip: Even for a single column, `df[["City"]]` forces the output to remain a DataFrame rather than decaying into a Series.*

In [46]:
subset = world_population[["country", "world_share"]]

print("Datatype")
print(type(subset))

print("\nSubset")
print(subset)

Datatype
<class 'pandas.DataFrame'>

Subset
              country world_share
0               China     18.47 %
1               India     17.70 %
2       United States      4.25 %
3           Indonesia      3.51 %
4            Pakistan      2.83 %
..                ...         ...
230        Montserrat      0.00 %
231  Falkland Islands      0.00 %
232              Niue      0.00 %
233           Tokelau      0.00 %
234          Holy See      0.00 %

[235 rows x 2 columns]

**11.** `df.loc[]` — **Label-Based Selection:** `[row_label, col_label]`

`loc` works exclusively with **explicit index and column names.**

- **Rule**: When slicing with `loc` (`"r1":"r3"`), the endpoint is inclusive.

In [68]:
# Select a single cell:
world_population.loc[0, "country"]

'China'

In [67]:
# Select rows by label:
world_population.loc[0]

position                             1
country                          China
population               1,439,323,776
yearly_change                   0.39 %
net_change                   5,540,090
density_per_square_km              153
land_are_in_square_km        9,388,211
migrants_net                  -348,399
fertility_rate                     1.7
median_age                          38
urban_population                  61 %
world_share                    18.47 %
Name: 0, dtype: object

In [70]:
# Row slice: both 'r0' and 'r2' are INCLUDED
world_population.loc[0 : 5]

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
0,1,China,"1,439,323,776",0.39 %,"5,540,090",153,"9,388,211","-348,399",1.7,38,61 %,18.47 %
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %
2,3,United States,"331,002,651",0.59 %,"1,937,734",36,"9,147,420","954,806",1.8,38,83 %,4.25 %
3,4,Indonesia,"273,523,615",1.07 %,"2,898,047",151,"1,811,570","-98,955",2.3,30,56 %,3.51 %
4,5,Pakistan,"220,892,340",2.00 %,"4,327,022",287,"770,880","-233,379",3.6,23,35 %,2.83 %
5,6,Brazil,"212,559,417",0.72 %,"1,509,890",25,"8,358,140","21,200",1.7,33,88 %,2.73 %

In [72]:
# Select specific rows AND columns:
world_population.loc[0: 10, ["country", "world_share"]]

          country world_share
0           China     18.47 %
1           India     17.70 %
2   United States      4.25 %
3       Indonesia      3.51 %
4        Pakistan      2.83 %
5          Brazil      2.73 %
6         Nigeria      2.64 %
7      Bangladesh      2.11 %
8          Russia      1.87 %
9          Mexico      1.65 %
10          Japan      1.62 %

In [77]:
# Conditional row filtering with loc:
world_population.loc[world_population["position"] > 10, ["country", "world_share"]]

              country world_share
10              Japan      1.62 %
11           Ethiopia      1.47 %
12        Philippines      1.41 %
13              Egypt      1.31 %
14            Vietnam      1.25 %
..                ...         ...
230        Montserrat      0.00 %
231  Falkland Islands      0.00 %
232              Niue      0.00 %
233           Tokelau      0.00 %
234          Holy See      0.00 %

[225 rows x 2 columns]

In [79]:
world_population.loc[(world_population["position"] > 10) & (world_population["position"] < 20), ["country", "world_share"]]

        country world_share
10        Japan      1.62 %
11     Ethiopia      1.47 %
12  Philippines      1.41 %
13        Egypt      1.31 %
14      Vietnam      1.25 %
15     DR Congo      1.15 %
16       Turkey      1.08 %
17         Iran      1.08 %
18      Germany      1.07 %

**12.** `df.iloc[]` — **Integer Position-Based Selection:** `[row_idx, col_idx]`

`iloc` (integer location) completely ignores index labels and column names, relying strictly on **zero-based numeric coordinates ($0, 1, 2, \dots$)**, identical to NumPy.

- **Rule**: Slicing with `iloc` follows standard Python rules: the end index is **exclusive**.

In [78]:
print(world_population.iloc[0:2, 0:2])

   position country
0         1   China
1         2   India

**13.** `isin()` — **Multiple OR Conditions for Values**

Instead of writing 

`(df["City"] == "Paris") | (df["City"] == "Rome") | (df["City"] == "Berlin")`, 

pass an iterable (list, set, tuple) to `isin()`.

- It generates a **boolean mask** (`True` if the element matches anything in the list).

In [80]:
# Select rows where city is either India, China and Indonesia
cities = ["India", "China", "Indonesia"]
world_population[world_population["country"].isin(cities)]

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
0,1,China,"1,439,323,776",0.39 %,"5,540,090",153,"9,388,211","-348,399",1.7,38,61 %,18.47 %
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %
3,4,Indonesia,"273,523,615",1.07 %,"2,898,047",151,"1,811,570","-98,955",2.3,30,56 %,3.51 %

**14.** Negation (NOT IN)

Prefix the condition with `~` to exclude items:

In [82]:
# Select rows where city is NOT in India, China and Indonesia
cities = ["India", "China", "Indonesia"]
world_population[~world_population["country"].isin(cities)]

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
2,3,United States,"331,002,651",0.59 %,"1,937,734",36,"9,147,420","954,806",1.8,38,83 %,4.25 %
4,5,Pakistan,"220,892,340",2.00 %,"4,327,022",287,"770,880","-233,379",3.6,23,35 %,2.83 %
5,6,Brazil,"212,559,417",0.72 %,"1,509,890",25,"8,358,140","21,200",1.7,33,88 %,2.73 %
6,7,Nigeria,"206,139,589",2.58 %,"5,175,990",226,"910,770","-60,000",5.4,18,52 %,2.64 %
7,8,Bangladesh,"164,689,383",1.01 %,"1,643,222","1,265","130,170","-369,501",2.1,28,39 %,2.11 %
...,...,...,...,...,...,...,...,...,...,...,...,...
230,231,Montserrat,"4,992",0.06 %,3,50,100,,N.A.,N.A.,10 %,0.00 %
231,232,Falkland Islands,"3,480",3.05 %,103,0,"12,170",,N.A.,N.A.,66 %,0.00 %
232,233,Niue,"1,626",0.68 %,11,6,260,,N.A.,N.A.,46 %,0.00 %
233,234,Tokelau,"1,357",1.27 %,17,136,10,,N.A.,N.A.,0 %,0.00 %
234,235,Holy See,801,0.25 %,2,"2,003",0,,N.A.,N.A.,N.A.,0.00 %

**15.** `between()` — **Range Filtering (Lower & Upper Bound)**

Instead of writing `(df["Age"] >= 25) & (df["Age"] <= 35)`, `between()` checks whether numeric or datetime values fall inside a range.

- **Syntax**: `df["col"].between(left, right, inclusive="both")`
- `inclusive` options: `"both"` (default), `"neither"`, `"left"`, or `"right"`.

In [ ]:
# Filter position between 50 and 60 (inclusive)
world_population[world_population["position"].between(50, 60)]

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
49,50,Venezuela,"28,435,940",-0.28 %,"-79,889",32,"882,050","-653,249",2.3,30,N.A.,0.36 %
50,51,Madagascar,"27,691,018",2.68 %,"721,711",48,"581,795","-1,500",4.1,20,39 %,0.36 %
51,52,Cameroon,"26,545,863",2.59 %,"669,483",56,"472,710","-4,800",4.6,19,56 %,0.34 %
52,53,Côte d'Ivoire,"26,378,274",2.57 %,"661,730",83,"318,000","-8,000",4.7,19,51 %,0.34 %
53,54,North Korea,"25,778,816",0.44 %,"112,655",214,"120,410","-5,403",1.9,35,63 %,0.33 %
54,55,Australia,"25,499,884",1.18 %,"296,686",3,"7,682,300","158,246",1.8,38,86 %,0.33 %
55,56,Niger,"24,206,644",3.84 %,"895,929",19,"1,266,700","4,000",7.0,15,17 %,0.31 %
56,57,Taiwan,"23,816,775",0.18 %,"42,899",673,"35,410","30,001",1.2,42,79 %,0.31 %
57,58,Sri Lanka,"21,413,249",0.42 %,"89,516",341,"62,710","-97,986",2.2,34,18 %,0.27 %
58,59,Burkina Faso,"20,903,273",2.86 %,"581,895",76,"273,600","-25,000",5.2,18,31 %,0.27 %
59,60,Mali,"20,250,833",3.02 %,"592,802",17,"1,220,190","-40,000",5.9,16,44 %,0.26 %

In [ ]:
# Exclusive Range Check
# Position > 4 AND Position < 8
world_population[world_population["position"].between(4,8, inclusive="neither")]

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
4,5,Pakistan,"220,892,340",2.00 %,"4,327,022",287,"770,880","-233,379",3.6,23,35 %,2.83 %
5,6,Brazil,"212,559,417",0.72 %,"1,509,890",25,"8,358,140","21,200",1.7,33,88 %,2.73 %
6,7,Nigeria,"206,139,589",2.58 %,"5,175,990",226,"910,770","-60,000",5.4,18,52 %,2.64 %

**16.** `query()` — **SQL-Style String Expressions**

`df.query()` evaluates an expression string. It eliminates repetitive references like `df[...]` and handles complex logical expressions cleanly.

**Basic Comparisons and Multiple Conditions**

Inside the query string, use standard words like `and`, `or`, `in`, and `not`.

In [86]:
world_population.query("country == 'India'")

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %

In [89]:
world_population.query("country in ['India', 'China']")

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
0,1,China,"1,439,323,776",0.39 %,"5,540,090",153,"9,388,211","-348,399",1.7,38,61 %,18.47 %
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %

In [91]:
country = "India"
world_population.query("country == @country")

,position,country,population,yearly_change,net_change,density_per_square_km,land_are_in_square_km,migrants_net,fertility_rate,median_age,urban_population,world_share
1,2,India,"1,380,004,385",0.99 %,"13,586,631",464,"2,973,190","-532,687",2.2,28,35 %,17.70 %

In [3]:
data = {
    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [15.0, np.nan, 35.0, np.nan],
    "city": ["New York", "London", np.nan, "Tokyo"],
    "socre": [90.0, 85.0, np.nan, np.nan]
}
df = pd.DataFrame(data)

In [4]:
df

      name   age      city  socre
0    Alice  15.0  New York   90.0
1      Bob   NaN    London   85.0
2  Charlie  35.0       NaN    NaN
3    David   NaN     Tokyo    NaN

**1.** `df.isnull()` **&** `df.isna()` — **Detect Missing Values**

`isnull()` and `isna()` are **exact aliases** of each other. They do the identical thing: return a boolean grid marking `True` where a value is missing (`NaN` or `None`) and `False` elsewhere.

In [5]:
df.isna()

    name    age   city  socre
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False   True  False   True

In [6]:
df.isnull()

    name    age   city  socre
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False   True  False   True

**Common Pattern: Count missing values per column**

Pair it with `.sum()` to see how dirty your dataset is:

In [7]:
df.isna().sum()

name     0
age      2
city     1
socre    2
dtype: int64

**2.** `df.notna()` — **Detect Non-Missing Values**

The direct inverse of `isna()`. It marks `True` for valid, populated cells and `False` for missing ones.

In [9]:
# Filter rows where 'city' is NOT missing
df[df["city"].notna()]

    name   age      city  socre
0  Alice  15.0  New York   90.0
1    Bob   NaN    London   85.0
3  David   NaN     Tokyo    NaN

**3.** `df.dropna()` — **Drop Rows or Columns with Missing Values**

Deletes any row or column containing missing data.

**Drop any row containing at least one** `NaN` **(Default)**

In [10]:
df.dropna()

    name   age      city  socre
0  Alice  15.0  New York   90.0

**Drop only if a specific column is missing (subset)**

In [12]:
df.dropna(subset=["age"])

      name   age      city  socre
0    Alice  15.0  New York   90.0
2  Charlie  35.0       NaN    NaN

**Drop entire columns that contain missing values**

In [13]:
df.dropna(axis=1)

      name
0    Alice
1      Bob
2  Charlie
3    David

**Drop only if ALL values are missing**

In [14]:
df.dropna(how="all")

      name   age      city  socre
0    Alice  15.0  New York   90.0
1      Bob   NaN    London   85.0
2  Charlie  35.0       NaN    NaN
3    David   NaN     Tokyo    NaN

**4.** `df.fillna()` — **Replace Missing Values with a Constant**

Fills all `NaN` slots across the DataFrame (or a specific Series) with a chosen replacement value instead of deleting rows.

In [16]:
df.fillna("Missing")

      name      age      city    socre
0    Alice     15.0  New York     90.0
1      Bob  Missing    London     85.0
2  Charlie     35.0   Missing  Missing
3    David  Missing     Tokyo  Missing

In [18]:
df.fillna({
    "city": "Unknown",
    "socre": 0.0
})

      name   age      city  socre
0    Alice  15.0  New York   90.0
1      Bob   NaN    London   85.0
2  Charlie  35.0   Unknown    0.0
3    David   NaN     Tokyo    0.0

**5.** `df["age"].fillna(df["age"].mean())` — **Mean Imputation**

This is a standard feature engineering pattern in machine learning called **mean imputation**. It replaces missing numeric values with the mathematical average of the non-missing values in that column.

How it evaluates:

1. `df["age"].mean()` calculates: $\frac{25.0 + 35.0}{2} = 30.0$ (ignoring the `NaN` s).
2. `.fillna(30.0)` substitutes every `NaN` in age with `30.0`.

In [ ]:
df["age"] = df["age"].fillna(df["age"].mean())

In [21]:
df

      name   age      city  socre
0    Alice  15.0  New York   90.0
1      Bob  25.0    London   85.0
2  Charlie  35.0       NaN    NaN
3    David  25.0     Tokyo    NaN

*Tip: If data has extreme outliers, use `df["age"].median()` instead of `.mean()`. For categorical data (like city), use mode: `df["city"].fillna(df["city"].mode()[0])`.*

In [22]:
data = {
    "Email": ["a@test.com", "b@test.com", "a@test.com", "c@test.com", "a@test.com"],
    "Name": ["Alice", "Bob", "Alice", "Charlie", "Alicia"],
    "Score": [90, 85, 90, 70, 95]
}
df = pd.DataFrame(data)
df

        Email     Name  Score
0  a@test.com    Alice     90
1  b@test.com      Bob     85
2  a@test.com    Alice     90
3  c@test.com  Charlie     70
4  a@test.com   Alicia     95

**1.** `df.duplicated()` —**Detect Duplicates**

Returns a boolean Series marking `True` for every row identified as a duplicate.

Default behavior (`keep='first'`)
The first occurrence is marked `False` (original), and subsequent identical rows are marked `True`.

In [23]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [24]:
df.duplicated().sum()

np.int64(1)

In [25]:
df[df.duplicated()]

        Email   Name  Score
2  a@test.com  Alice     90

In [27]:
df.duplicated(subset=["Email"])

0    False
1    False
2     True
3    False
4     True
dtype: bool

**The** `keep` **parameter options:**

`keep="first"` (default): Marks duplicates as `True`, except for the first occurrence.

`keep="last"`: Marks duplicates as `True`, except for the last occurrence.

`keep=False`: Marks all copies of duplicate rows as `True` (useful for inspecting all offending records).

In [28]:
df[df.duplicated(subset=["Email"], keep=False)]

        Email    Name  Score
0  a@test.com   Alice     90
2  a@test.com   Alice     90
4  a@test.com  Alicia     95

**2.** `df.drop_duplicates()` — **Remove Duplicates**

Returns a new DataFrame with duplicate rows deleted.

In [29]:
df.drop_duplicates()

        Email     Name  Score
0  a@test.com    Alice     90
1  b@test.com      Bob     85
3  c@test.com  Charlie     70
4  a@test.com   Alicia     95

In [31]:
df.drop_duplicates(subset=["Email"], keep="first")

        Email     Name  Score
0  a@test.com    Alice     90
1  b@test.com      Bob     85
3  c@test.com  Charlie     70

In [32]:
df.drop_duplicates(subset=["Email"], keep="last")

        Email     Name  Score
1  b@test.com      Bob     85
3  c@test.com  Charlie     70
4  a@test.com   Alicia     95

Modify the DataFrame in-place

To overwrite the original DataFrame without reassigning:

In [33]:
df.drop_duplicates(subset=["Email"], inplace=True)

In [34]:
df

        Email     Name  Score
0  a@test.com    Alice     90
1  b@test.com      Bob     85
3  c@test.com  Charlie     70

In [36]:
import pandas as pd

data = {
    "emp_id": ["101", "102", "103"],
    "salary_str": ["50000", "65000", "80000"],
    "dept_code": ["D1", "D2", "D1"],
    "bonus": [1000, 1500, 2000]
}
df = pd.DataFrame(data)
df

  emp_id salary_str dept_code  bonus
0    101      50000        D1   1000
1    102      65000        D2   1500
2    103      80000        D1   2000

**1.** `df.rename()` — **Rename Columns or Index Labels**

Alters column names or row indices by passing a dictionary mapping `{old_name: new_name}`. Unmentioned columns remain untouched.

In [37]:
df.rename(columns={
    "emp_id": "employee_id",
    "dept_code": "department_code"
})

  employee_id salary_str department_code  bonus
0         101      50000              D1   1000
1         102      65000              D2   1500
2         103      80000              D1   2000

Tip: You can also rename using a function, like converting all headers to lowercase:

In [38]:
df.rename(columns=str.upper)

  EMP_ID SALARY_STR DEPT_CODE  BONUS
0    101      50000        D1   1000
1    102      65000        D2   1500
2    103      80000        D1   2000

**2.** `df.astype()` — **Cast / Convert Data Types**

Casts columns from one data type to another (e.g., string to `int64`, `float64`, `category`, or `bool`).

In [39]:
df["salary_str"].dtype

In [40]:
df["salary_str"].astype(int)

0    50000
1    65000
2    80000
Name: salary_str, dtype: int64

In [41]:
df = df.astype({
    "emp_id": int,
    "salary_str": float,
    "dept_code": "category"
})

In [42]:
df.dtypes

emp_id           int64
salary_str     float64
dept_code     category
bonus            int64
dtype: object

**3.** `df.replace()` — **Swap Specific Values**

Replaces specific targets (exact values, lists, or regex patterns) across an entire DataFrame or a single column. Unlike `fillna()`, it works on non-null values too.

In [45]:
df

   emp_id  salary_str dept_code  bonus
0     101     50000.0        D1   1000
1     102     65000.0        D2   1500
2     103     80000.0        D1   2000

In [49]:
df["dept_code"] = df["dept_code"].astype(str)

In [50]:
df["dept_code"] = df["dept_code"].replace({
    "D1": "Engineering",
    "D2": "Marketing"
})
df

   emp_id  salary_str    dept_code  bonus
0     101     50000.0  Engineering      0
1     102     65000.0    Marketing      0
2     103     80000.0  Engineering   2000

In [48]:
df["bonus"] = df["bonus"].replace([1000, 1500], 0)
df

   emp_id  salary_str dept_code  bonus
0     101     50000.0        D1      0
1     102     65000.0        D2      0
2     103     80000.0        D1   2000

**4.** `df["col"].map()` **— 1-to-1 Element Substitution (Series Only)**

Called on a **single column (Series)** to substitute each value using a dictionary or a custom single-argument function.

**Crucial Difference from** `replace()`: If a key is not found in the dictionary, `map()` replaces it with NaN, whereas `replace()` keeps the original value intact.

In [51]:
tier_lookup = {
    "Engineering": "Technical",
    "Marketing": "Business"
}

# Map categories
df["dept_type"] = df["dept_code"].map(tier_lookup)
df

   emp_id  salary_str    dept_code  bonus  dept_type
0     101     50000.0  Engineering      0  Technical
1     102     65000.0    Marketing      0   Business
2     103     80000.0  Engineering   2000  Technical

In [52]:
# Using map with a lambda function
df["bonus_mapped"] = df["bonus"].map(lambda x: f"${x}")

In [53]:
df

   emp_id  salary_str    dept_code  bonus  dept_type bonus_mapped
0     101     50000.0  Engineering      0  Technical           $0
1     102     65000.0    Marketing      0   Business           $0
2     103     80000.0  Engineering   2000  Technical        $2000

**5.** `df.apply()` — **Apply Functions Along an Axis**

Runs a custom function across an entire Series, or across rows/columns of a DataFrame.

**Case A: On a single column (Series)**

Passes each individual cell value into the function.

In [54]:
df["salary_raised"] = df["salary_str"].apply(lambda s: s * 1.10)

In [55]:
df

,emp_id,salary_str,dept_code,bonus,dept_type,bonus_mapped,salary_raised
0,101,50000.0,Engineering,0,Technical,$0,55000.0
1,102,65000.0,Marketing,0,Business,$0,71500.0
2,103,80000.0,Engineering,2000,Technical,$2000,88000.0

**Case B: On a full DataFrame (`axis=1` -> row-wise)**

Allows combining multiple columns inside a single function row-by-row.

In [58]:
# Calculate total compensation: Salary + Bonus for every row
def total_comp(row):
    return row["salary_str"] + row["bonus"]

# axis=1 passes each row as a Series into the function
df["total_pay"] = df.apply(total_comp, axis=1)

In [59]:
df

,emp_id,salary_str,dept_code,bonus,dept_type,bonus_mapped,salary_raised,total_pay
0,101,50000.0,Engineering,0,Technical,$0,55000.0,50000.0
1,102,65000.0,Marketing,0,Business,$0,71500.0,65000.0
2,103,80000.0,Engineering,2000,Technical,$2000,88000.0,82000.0

These two methods order your data in Pandas: `df.sort_values()` sorts by the data inside columns, while `df.sort_index()` sorts by the row or column labels (index).

In [61]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Score": [88, 95, 72, 95],
    "Age": [25, 30, 22, 20]
}
df = pd.DataFrame(data, index=[3,1,4,2])
df

      Name  Score  Age
3    Alice     88   25
1      Bob     95   30
4  Charlie     72   22
2    David     95   20

**1.** `df.sort_values()` — **Sort by Content**
Reorders rows based on the values in one or more specified columns.

**Single Column (Ascending vs. Descending)**
- Default is ascending order (`ascending=True`).

In [ ]:
# Sort by Score: lowest to highest
df.sort_values(by="Score")

      Name  Score  Age
4  Charlie     72   22
3    Alice     88   25
1      Bob     95   30
2    David     95   20

In [64]:
# Sort by Score: highest to lowest
df.sort_values(by="Score", ascending=False)

      Name  Score  Age
1      Bob     95   30
2    David     95   20
3    Alice     88   25
4  Charlie     72   22

**Multiple Columns (Tie-Breaking)**

Pass a list of column names to `by`. You can set independent sorting directions for each column using a list of booleans in `ascending`.

In [66]:
df.sort_values(
    by=["Score", "Age"],
    ascending=[False, True]
)

      Name  Score  Age
2    David     95   20
1      Bob     95   30
3    Alice     88   25
4  Charlie     72   22

**Handling Missing Values (na_position)**

Control whether `NaN` values appear at the beginning or the end:

In [67]:
df.sort_values(by="Score", na_position="first")

      Name  Score  Age
4  Charlie     72   22
3    Alice     88   25
1      Bob     95   30
2    David     95   20

**2.** `df.sort_index()` — **Sort by the Index / Labels**

Reorders rows or columns by their labels, ignoring the values stored inside the table. This is commonly used after `groupby()`, `value_counts()`, or shuffling operations to restore chronological or numeric order.

Sort Row Index (`axis=0`, default)

In [68]:
df.sort_index()

      Name  Score  Age
1      Bob     95   30
2    David     95   20
3    Alice     88   25
4  Charlie     72   22

In [ ]:
# Descending Row Index
df.sort_index(ascending=False)

      Name  Score  Age
4  Charlie     72   22
3    Alice     88   25
2    David     95   20
1      Bob     95   30

**Sort Column Headers Alphabetically** (`axis=1`)

In [ ]:
# Reorder columns alphabetically: Age, Name, Score
df.sort_index(axis=1)

   Age     Name  Score
3   25    Alice     88
1   30      Bob     95
4   22  Charlie     72
2   20    David     95

In [72]:
data = {
    "Department": ["Sales", "Sales", "IT", "IT", "HR", "Sales"],
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank"],
    "Salary": [60000, 65000, 85000, 90000, 50000, 70000],
    "Bonus": [5000, 7000, 8000, 9500, 3000, 6000]
}
df = pd.DataFrame(data)
df

  Department Employee  Salary  Bonus
0      Sales    Alice   60000   5000
1      Sales      Bob   65000   7000
2         IT  Charlie   85000   8000
3         IT    David   90000   9500
4         HR      Eve   50000   3000
5      Sales    Frank   70000   6000

**1. Basic Grouping with a Single Aggregation**

Group by a categorical column and calculate a summary statistic across numerical columns.

In [75]:
# Average salary per department
df.groupby("Department")["Salary"].mean()

Department
HR       50000.0
IT       87500.0
Sales    65000.0
Name: Salary, dtype: float64

Common aggregation methods:

- `.mean()` — Average
- `.sum()` — Total sum
- `.count()` — Number of non-null rows
- `.min()` / `.max()` — Extremes
- `.std()` — Standard deviation

**2. Keeping the Group Column as a Regular Column** (`as_index=False`)

By default, the grouping column becomes the new row index. Use `as_index=False` to keep it as a standard column (similar to an SQL `GROUP BY`).

In [76]:
df.groupby("Department", as_index=False)["Salary"].mean()

  Department   Salary
0         HR  50000.0
1         IT  87500.0
2      Sales  65000.0

**3. Multiple Aggregations with** `.agg()`

Use `.agg()` when you need more than one statistic computed at once.

In [79]:
df.groupby("Department")["Salary"].agg(["min", "max", "mean"])

              min    max     mean
Department
HR          50000  50000  50000.0
IT          85000  90000  87500.0
Sales       60000  70000  65000.0

**Different metrics for different columns (Dictionary syntax):**

In [80]:
df.groupby("Department").agg({
    "Employee": "count",
    "Salary": "mean",
    "Bonus": "sum"
})

            Employee   Salary  Bonus
Department
HR                 1  50000.0   3000
IT                 2  87500.0  17500
Sales              3  65000.0  18000

**4. Grouping by Multiple Columns**

Pass a list of columns to group by nested sub-categories (e.g., Department and Office Location).

In [82]:
df.groupby(["Department", "Employee"])["Salary"].mean()

Department  Employee
HR          Eve         50000.0
IT          Charlie     85000.0
            David       90000.0
Sales       Alice       60000.0
            Bob         65000.0
            Frank       70000.0
Name: Salary, dtype: float64

**5.** `transform()` **vs.** `agg()` **(Advanced & Very Common in ML)**
- `.agg()` shrinks rows down to one row per unique group.
- `.transform()` performs the group calculation but returns an output matching the **original DataFrame's size**, making it easy to attach back as a new feature column.

In [85]:
# Add each department's average salary directly as a column
df["Dept_Avg_Salary"] = df.groupby("Department")["Salary"].transform("mean")
df

  Department Employee  Salary  Bonus  Dept_Avg_Salary
0      Sales    Alice   60000   5000          65000.0
1      Sales      Bob   65000   7000          65000.0
2         IT  Charlie   85000   8000          87500.0
3         IT    David   90000   9500          87500.0
4         HR      Eve   50000   3000          50000.0
5      Sales    Frank   70000   6000          65000.0

In [86]:
# Calculate how much an employee earns above or below their department average
df["Diff_From_Dept_Avg"] = df["Salary"] - df["Dept_Avg_Salary"]
df

  Department Employee  Salary  Bonus  Dept_Avg_Salary  Diff_From_Dept_Avg
0      Sales    Alice   60000   5000          65000.0             -5000.0
1      Sales      Bob   65000   7000          65000.0                 0.0
2         IT  Charlie   85000   8000          87500.0             -2500.0
3         IT    David   90000   9500          87500.0              2500.0
4         HR      Eve   50000   3000          50000.0                 0.0
5      Sales    Frank   70000   6000          65000.0              5000.0

In [87]:
# Employees table
df_emp = pd.DataFrame({
    "emp_id": [1, 2, 3, 4],
    "name": ["Alice", "Bob", "Charlie", "David"],
    "dept_id": [10, 20, 10, 99]  # Note: dept_id 99 doesn't exist in df_dept
})
print("Employee Data")
print(df_emp)

# Departments table
df_dept = pd.DataFrame({
    "dept_id": [10, 20, 30],       # Note: dept_id 30 has no employees
    "dept_name": ["Engineering", "HR", "Marketing"]
})
print("\n\nDepartment Data")
print(df_dept)

Employee Data
   emp_id     name  dept_id
0       1    Alice       10
1       2      Bob       20
2       3  Charlie       10
3       4    David       99


Department Data
   dept_id    dept_name
0       10  Engineering
1       20           HR
2       30    Marketing

**1.** **The Four Join Types (`how=`)**

The `how` parameter dictates which rows are kept when keys do not match across both tables.

**Inner Join (`how="inner"`, default)**

Keeps only rows where the key exists in **both** DataFrames (intersection).

In [88]:
pd.merge(df_emp, df_dept, on="dept_id", how="inner")

   emp_id     name  dept_id    dept_name
0       1    Alice       10  Engineering
1       2      Bob       20           HR
2       3  Charlie       10  Engineering

**Left Join (`how="left"`)**

Keeps **all rows from the left table** (`df_emp`). Missing matches from the right table become `NaN`.

In [89]:
pd.merge(df_emp, df_dept, on="dept_id", how="left")

   emp_id     name  dept_id    dept_name
0       1    Alice       10  Engineering
1       2      Bob       20           HR
2       3  Charlie       10  Engineering
3       4    David       99          NaN

**Left Join (`how="left"`)**

Keeps all rows from the left table (`df_emp`). Missing matches from the right table become `NaN`.

In [90]:
pd.merge(df_emp, df_dept, on="dept_id", how="right")

   emp_id     name  dept_id    dept_name
0     1.0    Alice       10  Engineering
1     3.0  Charlie       10  Engineering
2     2.0      Bob       20           HR
3     NaN      NaN       30    Marketing

**Outer Join (`how="outer"`)**

Keeps **all rows from both tables** (union), filling non-matches with `NaN`.

In [91]:
pd.merge(df_emp, df_dept, on="dept_id", how="outer")

   emp_id     name  dept_id    dept_name
0     1.0    Alice       10  Engineering
1     3.0  Charlie       10  Engineering
2     2.0      Bob       20           HR
3     NaN      NaN       30    Marketing
4     4.0    David       99          NaN

**2. Handling Different Column Names:** `left_on` and `right_on`

When the key columns have different names in each table, map them explicitly:

In [92]:
df_roles = pd.DataFrame({
    "id": [1, 2],
    "role": ["Dev", "Recruiter"]
})
df_roles

   id       role
0   1        Dev
1   2  Recruiter

In [93]:
# Merge employee table on 'emp_id' with roles table on 'id'
pd.merge(df_emp, df_roles, left_on="emp_id", right_on="id", how="inner")

   emp_id   name  dept_id  id       role
0       1  Alice       10   1        Dev
1       2    Bob       20   2  Recruiter

**3. Handling Overlapping Non-Key Column Names:** `suffixes`

If both DataFrames share a column that isn't the merge key, Pandas appends `_x` and `_y` by default. Customize this with `suffixes`:

In [95]:
df1 = pd.DataFrame({"id": [1], "location": ["NY"]})
df2 = pd.DataFrame({"id": [1], "location": ["London"]})

pd.merge(df1, df2, on="id", suffixes=("_hq", "_branch"))

   id location_hq location_branch
0   1          NY          London

**4. Merging on Index:** `left_index` and `right_index`

If a merge key resides in the index rather than a regular column:

In [96]:
# Use the row index of df_dept instead of a column
df_dept_indexed = df_dept.set_index("dept_id")

pd.merge(df_emp, df_dept_indexed, left_on="dept_id", right_index=True, how="left")

   emp_id     name  dept_id    dept_name
0       1    Alice       10  Engineering
1       2      Bob       20           HR
2       3  Charlie       10  Engineering
3       4    David       99          NaN

**5. Tracking Match Origin:** `indicator=True`

Adds a special `_merge` column showing whether a record came from `both`, `left_only`, or `right_only`.

In [97]:
merged = pd.merge(df_emp, df_dept, on="dept_id", how="outer", indicator=True)
print(merged[["emp_id", "dept_id", "_merge"]])

   emp_id  dept_id      _merge
0     1.0       10        both
1     3.0       10        both
2     2.0       20        both
3     NaN       30  right_only
4     4.0       99   left_only

In [98]:
df = pd.DataFrame({
    "Date": ["Mon", "Mon", "Tue", "Tue", "Mon"],
    "City": ["NYC", "LA",  "NYC", "LA",  "NYC"],
    "Temp": [70,    80,    72,    82,    68]  # Note: 2 entries for Mon-NYC (70 and 68)
})
df

  Date City  Temp
0  Mon  NYC    70
1  Mon   LA    80
2  Tue  NYC    72
3  Tue   LA    82
4  Mon  NYC    68

**1.** `df.pivot()` — **Reshape Wide (No Aggregation)**

Turns unique values from one column into new column headers. It reshapes data purely on a 1-to-1 basis.

- Critical Rule: `pivot()` cannot handle duplicate index/column pairs. If combinations repeat, it raises a `ValueError: Index contains duplicate entries`.

Using a clean slice without duplicates:

In [99]:
clearn_df = df.iloc[:4] # Rows 0 to 3 (unique combinations only)
clearn_df.pivot(index="Date", columns="City", values="Temp")

City  LA  NYC
Date
Mon   80   70
Tue   82   72

**2.** `pd.pivot_table()` — **Reshape Wide with Aggregation (Excel-Style)**

Functions like an Excel Pivot Table. It does everything `pivot()` does, but **safely handles duplicate entries** by aggregating them using `aggfunc` (defaults to `"mean"`).

**Handling Duplicates Automatically**

Because `df` has two readings for `Mon/NYC` (70 and 68), `pivot_table()` calculates their average (`69.0`):

In [100]:
# aggfunc='mean' by default
df.pivot_table(index="Date", columns="City", values="Temp")

City    LA   NYC
Date
Mon   80.0  69.0
Tue   82.0  72.0

**Custom Aggregations and Grand Totals (margins)**

In [101]:
df.pivot_table(
    index="Date",
    columns="City",
    values="Temp",
    aggfunc="max",
    margins=True,
    margins_name="Max_All"
)

City     LA  NYC  Max_All
Date
Mon      80   70       80
Tue      82   72       82
Max_All  82   72       82

**3.** `pd.melt()` — **Unpivot Wide to Long**

The exact inverse of pivoting. It takes multiple columns and unpivots them into row pairs (`variable` and `value`). This is crucial for Seaborn plotting and machine learning feature preparation.

In [102]:
wide_df = pd.DataFrame({
    "Student": ["Alice", "Bob"],
    "Math": [90, 75],
    "English": [85, 92]
})
wide_df

  Student  Math  English
0   Alice    90       85
1     Bob    75       92

**Melt it into Long Format:**

- `id_vars`: Columns to keep fixed as identifier variables.
- `value_vars`: Columns to unpivot (if omitted, melts all remaining columns).
- `var_name` / `value_name`: Names for the newly created columns.

In [103]:
pd.melt(
    wide_df,
    id_vars=["Student"],
    value_vars=["Math", "English"],
    var_name="Subject",
    value_name="Score"
)

  Student  Subject  Score
0   Alice     Math     90
1     Bob     Math     75
2   Alice  English     85
3     Bob  English     92

**1. Basic Conversion**

It automatically parses standard date string formats without extra configuration:

In [104]:
pd.to_datetime("2026-08-18")

Timestamp('2026-08-18 00:00:00')

In [107]:
df = pd.DataFrame({
    "date_str": ["2026-01-15", "2026-02-20", "2026-03-25"]
})

In [108]:
pd.to_datetime(df["date_str"])

0   2026-01-15
1   2026-02-20
2   2026-03-25
Name: date_str, dtype: datetime64[us]

2. Ambiguous Dates: `format=` and `dayfirst=`

Different countries format dates differently (e.g., `04/09/2026` could mean April 9th or September 4th). Use `format` or `dayfirst` to prevent misinterpretation and speed up parsing.

**Using** `dayfirst=True` **(European / Indian format: DD/MM/YYYY)**

In [111]:
s = pd.Series(["04/09/2026", "15/09/2026"])
s

0    04/09/2026
1    15/09/2026
dtype: str

In [112]:
pd.to_datetime(s, dayfirst=True)

0   2026-09-04
1   2026-09-15
dtype: datetime64[us]

**Explicit Format String** (`format=`)

Explicitly specifying the structure bypasses heuristic guessing, running much faster on large datasets.

In [115]:
date_strings = ["2026-Sep-18 09:30:00", "2026-Sep-19 14:15:00"]

# %Y = 4-digit year, %b = month abbrev, %d = day, %H = 24hr hour, %M = min, %S = sec
df = pd.DataFrame({
    "datetime": pd.to_datetime(date_strings, format="%Y-%b-%d %H:%M:%S")
})
df

             datetime
0 2026-09-18 09:30:00
1 2026-09-19 14:15:00

Common format tokens:

- `%Y `(2026) vs `%y` (26)
- `%m` (numeric 09) vs `%b` (Sep) vs `%B` (September)
- `%d` (day of month: 01–31)
- `%H` (00–23) vs `%I` (01–12) with `%p` (AM/PM)

**3. Handling Dirty / Malformed Data** (`errors=`)

Real-world datasets often contain junk data like `"unknown"`, `"N/A"`, or invalid dates like `"2026-02-30"`.

- `errors='raise'` (default): Throws an exception and stops execution.
- `errors='coerce'`: Replaces invalid values with `NaT` (Not a Time, Pandas' null for dates).

In [116]:
dirty_dates = ["2026-01-01", "not_a_date", "2026-02-31"]

pd.to_datetime(dirty_dates, errors="coerce")

DatetimeIndex(['2026-01-01', 'NaT', 'NaT'], dtype='datetime64[us]', freq=None)

**4. Parsing Multiple Columns into One Date**

If year, month, and day are stored in separate columns, pass the DataFrame slice directly:

In [118]:
df = pd.DataFrame({
    "year": [2026, 2026],
    "month": [9, 10],
    "day": [18, 5]
})

df["full_date"] = pd.to_datetime(df[["year", "month", "day"]])
print(df["full_date"])

0   2026-09-18
1   2026-10-05
Name: full_date, dtype: datetime64[us]

**5. Why Convert? The** `.dt` **Accessor & Date Math**

Once converted to `datetime64`, access date components and calculate elapsed time directly:

In [120]:
df = pd.DataFrame({"login_time": pd.to_datetime(["2026-09-18 14:30:00"])})

# Extract features
df["year"] = df["login_time"].dt.year                 # 2026
df["month_name"] = df["login_time"].dt.month_name()   # September
df["day_name"] = df["login_time"].dt.day_name()       # Friday
df["dayofweek"] = df["login_time"].dt.dayofweek       # 4 (0 is Monday)
df["hour"] = df["login_time"].dt.hour                 # 14

# Date arithmetic
now = pd.to_datetime("2026-09-20 14:30:00")
df["days_elapsed"] = (now - df["login_time"]).dt.days  # 2 days
df

           login_time  year month_name day_name  dayofweek  hour  days_elapsed
0 2026-09-18 14:30:00  2026  September   Friday          4    14             2